version: "3"
services:
  postgres:
    container_name: postgres-container
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "masterkey"    
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/src/api-node-ts-clean-identity
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    environment:
      - BASEDIR=./dist
      - SMTP_HOST=smtp.gmail.com
      - SMTP_USER=allan.gaby@gmail.com
      - SMTP_PASS=@D373c70R@
    volumes:
      - ./dist/:/usr/src/api-node-ts-clean-identity/dist/
      - ./temp/:/usr/src/api-node-ts-clean-identity/temp/
      - ./uploads/:/usr/src/api-node-ts-clean-identity/uploads/
      - ./src/infra/comunication/views/:/usr/src/api-node-ts-clean-identity/dist/infra/comunication/views/
      - ./package.json:/usr/src/api-node-ts-clean-identity/package.json
      - ./ormconfig.json:/usr/src/api-node-ts-clean-identity/ormconfig.json
    ports:
      - "3333:3333"
      - "9222:9222"
    links: 
      - postgres