version: "3"
services:
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/src/api-node-ts-clean-identity
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./dist/:/usr/src/api-node-ts-clean-identity/dist/
      - ./temp/:/usr/src/api-node-ts-clean-identity/temp/
      - ./uploads/:/usr/src/api-node-ts-clean-identity/uploads/
      - ./package.json:/usr/src/api-node-ts-clean-identity/package.json
    ports:
      - "3333:3333"
      - "9222:9222"