version: '3.5'

networks: 
  identity-net:
    name: identity-net

services:
  identity_api:
    container_name: 'identity_api'
    image: node:12
    working_dir: /opt/identity
    volumes:
      - ./public:/opt/identity/public
      - ./package.json:/opt/identity/package.json
      - ./.env:/opt/identity/.env
      - ./ormconfig.json:/opt/identity/ormconfig.json
    ports:
      - $PORT:$PORT
    command: bash -c "npm install --only=prod && npm run create-uploads-dir && npm run build:debug"
    depends_on:
      - db
      - rabbit
      - cache 
    networks: 
      - identity-net
    links: 
      - db
      - rabbit
      - cache
  db:
    container_name: identity-db
    image: postgres
    restart: always
    ports: 
      - $POSTGRES_PORT:5432
    volumes: 
      - ./data/postgres-data:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro    
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    networks: 
      - identity-net      
  cache:
    container_name: identity-cache
    image: redis:6-alpine
    restart: always
    ports: 
      - $REDIS_PORT:6379     
    volumes: 
      - ./data/redis:/data
    command: redis-server --requirepass $REDIS_PASSWORD       
    networks: 
      - identity-net    
  rabbit:
    image: rabbitmq:3.8.2-management
    container_name: rabbitmq-identity
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: identity
      RABBITMQ_DEFAULT_PASS: masterkey
      RABBITMQ_ERLANG_COOKIE: NW8j0hNXd6ySHRXEaYqlXZsYPalJ9F
      RABBITMQ_NODENAME: rabbit-identity
      TZ: America/Sao_Paulo
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo
    ports:
      - 5672:5672
      - 15672:15672
    networks: 
      - identity-net      